# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(523, 410)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title = QtWidgets.QLabel(self.centralWidget)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.verticalLayout.addWidget(self.title)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.seedLabel = QtWidgets.QLabel(self.centralWidget)
        self.seedLabel.setObjectName("seedLabel")
        self.horizontalLayout.addWidget(self.seedLabel)
        self.seedValue = QtWidgets.QLineEdit(self.centralWidget)
        self.seedValue.setObjectName("seedValue")
        self.horizontalLayout.addWidget(self.seedValue)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.starRodCheck = QtWidgets.QCheckBox(self.centralWidget)
        self.starRodCheck.setObjectName("starRodCheck")
        self.verticalLayout.addWidget(self.starRodCheck)
        self.noAbilityCheck = QtWidgets.QCheckBox(self.centralWidget)
        self.noAbilityCheck.setToolTip("")
        self.noAbilityCheck.setStatusTip("")
        self.noAbilityCheck.setObjectName("noAbilityCheck")
        self.verticalLayout.addWidget(self.noAbilityCheck)
        self.noRandoCheck = QtWidgets.QCheckBox(self.centralWidget)
        self.noRandoCheck.setObjectName("noRandoCheck")
        self.verticalLayout.addWidget(self.noRandoCheck)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.grayColor = QtWidgets.QRadioButton(self.centralWidget)
        self.grayColor.setObjectName("grayColor")
        self.gridLayout.addWidget(self.grayColor, 4, 2, 1, 1)
        self.orangeColor = QtWidgets.QRadioButton(self.centralWidget)
        self.orangeColor.setObjectName("orangeColor")
        self.gridLayout.addWidget(self.orangeColor, 2, 1, 1, 1)
        self.greenColor = QtWidgets.QRadioButton(self.centralWidget)
        self.greenColor.setObjectName("greenColor")
        self.gridLayout.addWidget(self.greenColor, 3, 1, 1, 1)
        self.lightGreenColor = QtWidgets.QRadioButton(self.centralWidget)
        self.lightGreenColor.setObjectName("lightGreenColor")
        self.gridLayout.addWidget(self.lightGreenColor, 3, 0, 1, 1)
        self.redColor = QtWidgets.QRadioButton(self.centralWidget)
        self.redColor.setObjectName("redColor")
        self.gridLayout.addWidget(self.redColor, 2, 0, 1, 1)
        self.yellowColor = QtWidgets.QRadioButton(self.centralWidget)
        self.yellowColor.setObjectName("yellowColor")
        self.gridLayout.addWidget(self.yellowColor, 2, 2, 1, 1)
        self.lightBlueColor = QtWidgets.QRadioButton(self.centralWidget)
        self.lightBlueColor.setObjectName("lightBlueColor")
        self.gridLayout.addWidget(self.lightBlueColor, 3, 2, 1, 1)
        self.purpleColor = QtWidgets.QRadioButton(self.centralWidget)
        self.purpleColor.setObjectName("purpleColor")
        self.gridLayout.addWidget(self.purpleColor, 4, 1, 1, 1)
        self.blueColor = QtWidgets.QRadioButton(self.centralWidget)
        self.blueColor.setObjectName("blueColor")
        self.gridLayout.addWidget(self.blueColor, 4, 0, 1, 1)
        self.randomColor = QtWidgets.QRadioButton(self.centralWidget)
        self.randomColor.setObjectName("randomColor")
        self.gridLayout.addWidget(self.randomColor, 1, 2, 1, 1)
        self.defaultColor = QtWidgets.QRadioButton(self.centralWidget)
        self.defaultColor.setChecked(True)
        self.defaultColor.setObjectName("defaultColor")
        self.gridLayout.addWidget(self.defaultColor, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.line = QtWidgets.QFrame(self.centralWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.romDisplay = QtWidgets.QLineEdit(self.centralWidget)
        self.romDisplay.setReadOnly(True)
        self.romDisplay.setObjectName("romDisplay")
        self.horizontalLayout_2.addWidget(self.romDisplay)
        self.findROMButton = QtWidgets.QPushButton(self.centralWidget)
        self.findROMButton.setObjectName("findROMButton")
        self.horizontalLayout_2.addWidget(self.findROMButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.line_2 = QtWidgets.QFrame(self.centralWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.randomizeButton = QtWidgets.QPushButton(self.centralWidget)
        self.randomizeButton.setObjectName("randomizeButton")
        self.verticalLayout.addWidget(self.randomizeButton)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.urlLabel = QtWidgets.QLabel(self.centralWidget)
        self.urlLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.urlLabel.setObjectName("urlLabel")
        self.verticalLayout.addWidget(self.urlLabel)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Kirby\'s Adventure Randomizer"))
        self.title.setText(_translate("MainWindow", "Kirby\'s Adventure Randomizer - Version: "))
        self.seedLabel.setText(_translate("MainWindow", "Seed:"))
        self.starRodCheck.setText(_translate("MainWindow", "Use Star Rod"))
        self.noAbilityCheck.setText(_translate("MainWindow", "Randomize enemies without abilities"))
        self.noRandoCheck.setText(_translate("MainWindow", "Don\'t Randomize, only change Kirby\'s color"))
        self.grayColor.setText(_translate("MainWindow", "Grayscale"))
        self.orangeColor.setText(_translate("MainWindow", "Orange"))
        self.greenColor.setText(_translate("MainWindow", "Green"))
        self.lightGreenColor.setText(_translate("MainWindow", "Light Green"))
        self.redColor.setText(_translate("MainWindow", "Red"))
        self.yellowColor.setText(_translate("MainWindow", "Yellow"))
        self.lightBlueColor.setText(_translate("MainWindow", "Light Blue"))
        self.purpleColor.setText(_translate("MainWindow", "Purple"))
        self.blueColor.setText(_translate("MainWindow", "Blue"))
        self.randomColor.setText(_translate("MainWindow", "Random"))
        self.defaultColor.setText(_translate("MainWindow", "Default (Pink)"))
        self.label.setText(_translate("MainWindow", "Kirby Color:"))
        self.findROMButton.setText(_translate("MainWindow", "Choose ROM Location"))
        self.randomizeButton.setText(_translate("MainWindow", "Randomize!"))
        self.urlLabel.setText(_translate("MainWindow", "https://github.com/Aquova/KA-Rando"))

